#Kubernetes Fibonacci calc app deployment on Google Cloud
sudo: required
services:
  - docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  #Once encrypted file is added to travis for the Github repo
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  #Setting Google cloud SDK in local machine
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  #Install and configure Kubectl
  - gcloud components update kubectl
  #Authenticate our SDK with our account (using service account)
  - gcloud auth activate-service-account --key-file service-account.json
  #Google CLI config:
  #Project ID configuration (G Cloud)
  - gcloud config set project rising-apricot-290114
  #Set zone
  - gcloud config set compute/zone europe-west2-a
  #Define K8s cluster to work with
  - gcloud container clusters get-credentials multi-cluster
  #Docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t eliasbedmar/react-test -f ./client/Dockerfile.dev ./client

#Testing script before deployment
script:
  - docker run -e CI=true eliasbedmar/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
